BibliothequeBundle\Entity\Cycle:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Entity\CycleRepository
    oneToMany:
        membres:
            targetEntity: Membre
            mappedBy: cycle
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbJours:
            type: integer
            column: nb_jours
        nbLivres:
            type: integer
            column: nb_livres
    lifecycleCallbacks: {  }
