BibliothequeBundle\Entity\Emprunt:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Entity\EmpruntRepository
    manyToOne:
        membre:
            targetEntity: Membre
            inversedBy: emprunts
            cascade: [ persist ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateDebut:
            type: date
            column: date_debut
        dateRetour:
            type: date
            column: date_retour
    lifecycleCallbacks: {  }
